### ISSUE TITLE
Aborted (core dumped) error when running ./hello

### ISSUE THREAD

**Issue by YuzhouPeng** [chesiy/cuda_resnet#10]
Hello, I run  ./hello and get the following error message:

(Tensorrt7.2.1) root@8265b51a85b4:/home/workspace/cuda_resnet# ./hello 
terminate called after throwing an instance of 'std::runtime_error'
  what():  Type is not convertible to double
Aborted (core dumped)

Before running ./hello, I did following steps:
1.Convert onnx file to weights.json using read_weight.py
2.Configure json weight file path in resnet18_main.cc run `make` command to generate exec file hello

How can I solve this issue? thank you

**Comment by biansy000** [comment]
With limited info, it is hard to find out why this error occurs. According to your report, maybe you could manually change the data type to float, and see whether it works fine then.

**Comment by YuzhouPeng** [comment]
I removed comment in        [     //    cout<<root[*it][i]<<'\n';](https://github.com/chesiy/cuda_resnet/blob/41d09018b5c6d02685497055f3a19a598802f459/resnet18_main.cc#L39)
and I get following errors:
(Tensorrt7.2.1) root@8265b51a85b4:/home/workspace/cuda_resnet# ./hello 
start init model

[

        [

                [
                        -0.002536008134484291,
                        -0.001493370626121759,
                        -0.0004404887149576098,
                        0.01821595802903175,
                        0.01377972029149532,
                        0.004157980903983116,
                        -0.003089616307988763
                ],

                [
                        0.002697465242817998,
                        0.002318955026566982,
                        -0.02675556205213070,
                        -0.06827221065759659,
                        -0.06601762026548386,
                        -0.03141606971621513,
                        0.0009108707308769226
                ],

                [
                        -0.001689970376901329,
                        0.01438190694898367,
                        0.07191862910985947,
                        0.1429200321435928,
                        0.1264965087175369,
                        0.06238780170679092,
                        0.01547318045049906
                ],

                [
                        0.007424630224704742,
                        -0.01631178893148899,
                        -0.07263156771659851,
                        -0.1067710742354393,
                        -0.06592398881912231,
                        -0.0001491562725277618,
                        0.01401998568326235
                ],

                [
                        -0.006701800972223282,
                        0.003905278630554676,
                        0.01766918785870075,
                        -0.01316802110522985,
                        -0.08101359009742737,
                        -0.1023656129837036,
                        -0.06275060772895813
                ],

                [
                        0.007450918667018414,
                        0.009969360195100307,
                        0.0152972387149930,
                        0.05816436186432838,
                        0.1007261946797371,
                        0.09579729288816452,
                        0.04041764140129089
                ],

                [
                        -0.003343292511999607,
                        -0.0008943653083406389,
                        -0.005861990153789520,
                        -0.01603409275412560,
                        -0.03667936101555824,
                        -0.02001423388719559,
                        -0.001407493487931788
                ]
        ],

        [

                [
                        -0.002774021821096539,
                        -0.006478924769908190,
                        -0.008431376889348030,
                        0.008959745056927204,
                        0.007915335707366467,
                        0.0001611777261132374,
                        -0.006265811622142792
                ],

                [
                        0.01111984997987747,
                        0.008178878575563431,
                        -0.02544134669005871,
                        -0.07517290115356445,
                        -0.07606750726699829,
                        -0.03906638547778130,
                        -0.0003121694608125836
                ],

                [
                        -0.0002037931699305773,
                        0.02395483665168285,
                        0.09786991775035858,
                        0.1874977648258209,
                        0.1722957342863083,
                        0.08978106081485748,
                        0.03031565621495247
                ],

                [
                        -0.001422083587385714,
                        -0.03130440413951874,
                        -0.1023972183465958,
                        -0.1442593485116959,
                        -0.09318304806947708,
                        -0.01032149605453014,
                        0.01498523820191622
                ],

                [
                        -0.01361200492829084,
                        -0.001271467888727784,
                        0.006591239478439093,
                        -0.03689532354474068,
                        -0.1123948469758034,
                        -0.1389300972223282,
                        -0.08896590769290924
                ],

                [
                        0.007998033426702023,
                        0.01352648437023163,
                        0.02425898239016533,
                        0.07743514329195023,
                        0.1329818964004517,
                        0.1175013557076454,
                        0.04835624992847443
                ],

                [
                        0.001291236258111894,
                        0.001629234175197780,
                        -0.004199597518891096,
                        -0.01699027791619301,
                        -0.03607682511210442,
                        -0.01880182512104511,
                        0.0001756889978423715
                ]
        ],

        [

                [
                        -0.0004944555694237351,
                        -0.002229895209893584,
                        0.005162260495126247,
                        0.02184590883553028,
                        0.02170507237315178,
                        0.008191524073481560,
                        -0.004892601631581783
                ],

                [
                        0.003747830633074045,
                        -0.004538815468549728,
                        -0.03064515441656113,
                        -0.07192958146333694,
                        -0.06168107315897942,
                        -0.03159236162900925,
                        -0.006809026934206486
                ],

                [
                        0.002396324183791876,
                        0.01193771045655012,
                        0.05281492695212364,
                        0.1046833470463753,
                        0.08487584441900253,
                        0.02539385110139847,
                        0.004481558687984943
                ],

                [
                        0.006431992631405592,
                        -0.006325804628431797,
                        -0.04794507101178169,
                        -0.06524424999952316,
                        -0.02561490610241890,
                        0.01912521757185459,
                        0.02939557284116745
                ],

                [
                        -0.006901706103235483,
                        0.004479483235627413,
                        0.02401011809706688,
                        0.01490583177655935,
                        -0.02857443504035473,
                        -0.06269908696413040,
                        -0.03760607168078423
                ],

                [
                        0.005054409150034189,
                        -0.0006397838005796075,
                        -0.009206263348460197,
                        0.01398310251533985,
                        0.05875824019312859,
                        0.05925403907895088,
                        0.02871014736592770
                ],

                [
                        0.0001817764132283628,
                        0.0001890623825602233,
                        -0.002446182537823915,
                        -0.01342379860579967,
                        -0.03618044406175613,
                        -0.02860767953097820,
                        -0.009334114380180836
                ]
        ]
]

terminate called after throwing an instance of 'std::runtime_error'
  what():  Type is not convertible to double
Aborted (core dumped)


Looks like the error happen when read json, but I generate the weight.json using provided onnx and read_weights.py in this repo

Could you possibily give solution to this problem?

**Comment by biansy000** [comment]
You may try using weight.json extracted by us ([google drive link](https://drive.google.com/file/d/1HfJVFpFxU_L8XRDsPPdoS6-dI17aSK7m/view?usp=sharing)), and see whether the problem still exists.

**Comment by YuzhouPeng** [comment]
I downloaded the weight and load but still got same error:

(Tensorrt7.2.1) root@8265b51a85b4:/home/workspace/cuda_resnet# ./hello 
start init model

[

        [

                [
                        -0.002536008134484291,
                        -0.001493370626121759,
                        -0.0004404887149576098,
                        0.01821595802903175,
                        0.01377972029149532,
                        0.004157980903983116,
                        -0.003089616307988763
                ],

                [
                        0.002697465242817998,
                        0.002318955026566982,
                        -0.02675556205213070,
                        -0.06827221065759659,
                        -0.06601762026548386,
                        -0.03141606971621513,
                        0.0009108707308769226
                ],

                [
                        -0.001689970376901329,
                        0.01438190694898367,
                        0.07191862910985947,
                        0.1429200321435928,
                        0.1264965087175369,
                        0.06238780170679092,
                        0.01547318045049906
                ],

                [
                        0.007424630224704742,
                        -0.01631178893148899,
                        -0.07263156771659851,
                        -0.1067710742354393,
                        -0.06592398881912231,
                        -0.0001491562725277618,
                        0.01401998568326235
                ],

                [
                        -0.006701800972223282,
                        0.003905278630554676,
                        0.01766918785870075,
                        -0.01316802110522985,
                        -0.08101359009742737,
                        -0.1023656129837036,
                        -0.06275060772895813
                ],

                [
                        0.007450918667018414,
                        0.009969360195100307,
                        0.0152972387149930,
                        0.05816436186432838,
                        0.1007261946797371,
                        0.09579729288816452,
                        0.04041764140129089
                ],

                [
                        -0.003343292511999607,
                        -0.0008943653083406389,
                        -0.005861990153789520,
                        -0.01603409275412560,
                        -0.03667936101555824,
                        -0.02001423388719559,
                        -0.001407493487931788
                ]
        ],

        [

                [
                        -0.002774021821096539,
                        -0.006478924769908190,
                        -0.008431376889348030,
                        0.008959745056927204,
                        0.007915335707366467,
                        0.0001611777261132374,
                        -0.006265811622142792
                ],

                [
                        0.01111984997987747,
                        0.008178878575563431,
                        -0.02544134669005871,
                        -0.07517290115356445,
                        -0.07606750726699829,
                        -0.03906638547778130,
                        -0.0003121694608125836
                ],

                [
                        -0.0002037931699305773,
                        0.02395483665168285,
                        0.09786991775035858,
                        0.1874977648258209,
                        0.1722957342863083,
                        0.08978106081485748,
                        0.03031565621495247
                ],

                [
                        -0.001422083587385714,
                        -0.03130440413951874,
                        -0.1023972183465958,
                        -0.1442593485116959,
                        -0.09318304806947708,
                        -0.01032149605453014,
                        0.01498523820191622
                ],

                [
                        -0.01361200492829084,
                        -0.001271467888727784,
                        0.006591239478439093,
                        -0.03689532354474068,
                        -0.1123948469758034,
                        -0.1389300972223282,
                        -0.08896590769290924
                ],

                [
                        0.007998033426702023,
                        0.01352648437023163,
                        0.02425898239016533,
                        0.07743514329195023,
                        0.1329818964004517,
                        0.1175013557076454,
                        0.04835624992847443
                ],

                [
                        0.001291236258111894,
                        0.001629234175197780,
                        -0.004199597518891096,
                        -0.01699027791619301,
                        -0.03607682511210442,
                        -0.01880182512104511,
                        0.0001756889978423715
                ]
        ],

        [

                [
                        -0.0004944555694237351,
                        -0.002229895209893584,
                        0.005162260495126247,
                        0.02184590883553028,
                        0.02170507237315178,
                        0.008191524073481560,
                        -0.004892601631581783
                ],

                [
                        0.003747830633074045,
                        -0.004538815468549728,
                        -0.03064515441656113,
                        -0.07192958146333694,
                        -0.06168107315897942,
                        -0.03159236162900925,
                        -0.006809026934206486
                ],

                [
                        0.002396324183791876,
                        0.01193771045655012,
                        0.05281492695212364,
                        0.1046833470463753,
                        0.08487584441900253,
                        0.02539385110139847,
                        0.004481558687984943
                ],

                [
                        0.006431992631405592,
                        -0.006325804628431797,
                        -0.04794507101178169,
                        -0.06524424999952316,
                        -0.02561490610241890,
                        0.01912521757185459,
                        0.02939557284116745
                ],

                [
                        -0.006901706103235483,
                        0.004479483235627413,
                        0.02401011809706688,
                        0.01490583177655935,
                        -0.02857443504035473,
                        -0.06269908696413040,
                        -0.03760607168078423
                ],

                [
                        0.005054409150034189,
                        -0.0006397838005796075,
                        -0.009206263348460197,
                        0.01398310251533985,
                        0.05875824019312859,
                        0.05925403907895088,
                        0.02871014736592770
                ],

                [
                        0.0001817764132283628,
                        0.0001890623825602233,
                        -0.002446182537823915,
                        -0.01342379860579967,
                        -0.03618044406175613,
                        -0.02860767953097820,
                        -0.009334114380180836
                ]
        ]
]

terminate called after throwing an instance of 'std::runtime_error'
  what():  Type is not convertible to double
Aborted (core dumped)

I think the layer of weights.json is different but I can not figure out how to solve it.

**Comment by biansy000** [comment]
Maybe you use a different version of jsoncpp? We use a rather old version of Jsoncpp. You can try to download it from [here](https://sourceforge.net/projects/jsoncpp/).

And there are two choices to install it.
1. You can install it following the instruction in README.md and delete ``json`` and ``lib_json`` folders provided in our main branch, because they are useless then.
2. You can follow [this](https://blog.csdn.net/nawenqiang/article/details/40509325?ops_request_misc=&request_id=&biz_id=102&utm_term=jsoncpp%E7%AE%80%E5%8D%95%E9%85%8D%E7%BD%AE&utm_medium=distribute.pc_search_result.none-task-blog-2~all~sobaiduweb~default-4-40509325.142^v26^pc_rank_34,157^v15^new_3&spm=1018.2226.3001.4187) and try "方法一".

**Comment by YuzhouPeng** [comment]
I tried to install json-cpp src5.0 and deleted libjson and json folder in project, but still got same error, maybe the error is not related jsoncpp?

**Comment by YuzhouPeng** [comment]
I tried to install json-cpp src5.0 and deleted libjson and json folder in project, but still got same error, maybe the error is not related jsoncpp?

**Comment by biansy000** [comment]
Sorry that I cannot reproduce the error you mentioned, and we've been busy lately.

Maybe you can try removing part of codes and see whether the problem still exists. 
For example, you may comment out all codes in the [main](https://github.com/chesiy/cuda_resnet/blob/41d09018b5c6d02685497055f3a19a598802f459/resnet18_main.cc#L106) function  in [resnet18_main.cc](https://github.com/chesiy/cuda_resnet/blob/main/resnet18_main.cc) except ``initModel();`` to check whether the problem exists in model initialization.
