### ISSUE TITLE
where is main.cpp?

### ISSUE THREAD

**Issue by YuzhouPeng** [chesiy/cuda_resnet#9]
你好，我这边查看cmakelist.txt并编译，但是没有找到main.cpp，然后我这边将onnx转为json之后，第二步要用pytorch搭建resnet18模型的脚本我没有看到，可以提供一下吗，非常感谢

**Comment by chesiy** [comment]
不要用cmakelist.txt编译，直接用makefile编译就可以。可以读一下makefile，main是resnet_main.cc

**Comment by biansy000** [comment]
You can check [code of resnet18](https://github.com/chesiy/cuda_resnet/blob/bsy/resnet.py), and [code for running resnet](https://github.com/chesiy/cuda_resnet/blob/bsy/try_resnet18.py). 

Resnet18 model is modified from [HybrIK](https://github.com/Jeff-sjtu/HybrIK) project.

**Comment by YuzhouPeng** [comment]
Thank you
